print('qual o seu nome? ')
nome=input()
print('bem vindo(a), ' +nome, 'ao estudo de python')
print('em que ano você nasceu?')
ano=int(input())
print ('e em que mês?')
mes=int(input())
print('e qual é o dia?')
dia=int(input())
print(dia, '/', mes, '/', ano)
print('------------------------------')
print('vamos fazer uma conta?')
n1=int(input('Digite um número: '))
n2=int(input('Digite outro número: '))
print('A soma entre {} e {} vale {}'.format(n1,n2,n1+n2))
